# language: crystal

# NOTE: DO NOT MERGE UPSTREAM (i.e.: DO NOT 'git push owner ...'; repo not owned by me)!!!

language: crystal

crystal:
  - latest
  - nightly

jobs:
  allow_failures:
    - crystal: latest

script:
  - crystal spec
  - crystal tool format --check
